#!/bin/sh

alias ls='ls --color=always'
alias grep='grep --color=always'
alias fgrep='fgrep --color=always'
alias egrep='egrep --color=always'

alias ll='ls -lh'
alias la='ls -Ah'
alias l='ls -CFh'
alias tree='tree -Ch'
alias b='cd ..'
alias rm='rm -i'

alias gits='git status'
alias gitl='git log'
alias gitb='git branch'

# Create an alias file for eshell
mkdir -p $HOME/.eshell
# http://www.emacswiki.org/emacs/EshellAlias
alias | sed -E "s/^alias ([^=]+)='(.*)'$/alias \1 \2 \$*/g; s/'\\\''/'/g;" > $HOME/.eshell/alias
