#!/bin/sh

alias l='ls -CFh'
alias la='ls -Ah'
alias ll='ls -lh'
alias ls='ls --color=always'

alias egrep='egrep --color=always'
alias fgrep='fgrep --color=always'
alias grep='grep --color=always'

alias b='cd ..'
alias rm='rm -i'
alias tree='tree -Ch'

# git aliases
alias gitd='git diff > /tmp/f.diff && DIFF_EDITOR=$EDITOR; if ! [[ -z "$(which emacsclient)" ]]; then DIFF_EDITOR="emacsclient -n " ; fi ; $DIFF_EDITOR /tmp/f.diff'
alias gits='git status'

# Create an alias file for eshell
mkdir -p $HOME/.eshell
# http://www.emacswiki.org/emacs/EshellAlias
alias | sed -E "s/^alias ([^=]+)='(.*)'$/alias \1 \2 \$*/g; s/'\\\''/'/g;" > $HOME/.eshell/alias
