#!/bin/bash
# exec grep "$@" | grep -v 'Binary file ..* matches' | fgrep -v '.svn'

if [ $# -lt 1 ]; then
	echo "Usage: bomgrep PATTERN"
	exit 1
fi

exec grep -nHs --color=always \
     --exclude="*.*pro[j]" \
     --exclude="*.[p]o" \
     --exclude="*.scons" \
     --exclude="*.sln" \
     --exclude="*ChangeLog*" \
     --exclude="Makefile" \
     --exclude="SConstruct" \
     --exclude="TAGS" \
     --exclude="config*" \
     --exclude-dir=".svn" \
     --exclude-dir=".output" \
     "$@" \
    | grep -v "Binary file ..* matches" \
    | sed -r 's/[\t]+//'
