#! /bin/sh

. $(dirname $0)/util.inc

function usage
{
    echo "kernel config path missing"
    echo "Usage:"
    echo -e "\t$ ./$(basename "$0") PATH"
}

function validate
{
    if [ "$1" == "--help" ]; then
        return 1
    fi

    if [ $# -lt 1 ]; then
        return 1
    fi

    # all ok
    KERNEL_CONFIG=$1
    return 0
}

function compile_kernel_and_install
{
    pushd "$PWD"
    cd /usr/src/linux

    /usr/bin/genkernel \
        --makeopts=-j$AVAILABLE_CPUS \
        --kernel-config=$KERNEL_CONFIG all \
    && /usr/sbin/grub-install /dev/sda \
    && /usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg

    popd

# make -s -j8 1>/tmp/kernel.log \
#  && make modules_install \
#  && genkernel --install initramfs \
#  && cp -v ./arch/x86_64/boot/bzImage /boot/kernel-$(uname -r) \
#  && /sbin/lilo
}

function build_kernel_dependent_application_modules
{
    PACKAGE_NAME=$1
    shift

    if [[ -z $PACKAGE_NAME ]]; then
        echo "missing package name"
        exit 1
    fi

    NOT_INSTALLED_MSG="No matches found"
    PACKAGE_INSTALLED=$(eix -Ic $PACKAGE_NAME)

    if [ "$PACKAGE_INSTALLED" == "$NOT_INSTALLED_MSG" ]; then
        return
    fi

    echo "installing '$PACKAGE_NAME' ..."

    if ! emerge -1 $PACKAGE_NAME ; then
        echo "failed"
        exit 1
    fi
}

validate $*
if [ $? -ne 0 ]; then
    usage
    exit 1
fi

# compile_kernel_and_install
build_kernel_dependent_application_modules app-emulation/virtualbox-modules
build_kernel_dependent_application_modules net-wireless/broadcom-sta
build_kernel_dependent_application_modules sys-firmware/b43-firmware
