#!/bin/bash
# A short program to open files directly from copy-paste from grep output in emacsclient.

if [ $# -lt 1 ]; then
    echo -e "Opens a file in emacs at a give line number (if any).\n\tUsage: em filename[:linenum[:anygarbagevalue]]"
    exit 1
fi

filename=$(echo $1 | cut -f1 -d ':')
linenum=$(echo $1 | cut -f2 -d ':')

echo -n "em: Opening '$filename' at line number $linenum... "

if [ -z $filename ]; then
    echo -e "Failed!\n** Filename cannot be extracted from given arguments"
    exit 1
fi

if ! [[ $linenum =~ ^[0-9]+$ ]] ; then
    echo -n "(cannot parse line number)... "
    linenum=0
fi

emacsclient -n +$linenum $filename
echo "done!"
