#!/bin/bash

# wrapper script for find program

if [ $# -lt 1 ]; then
        echo "Usage: $(basename $0) PATTERN"
        exit 1
fi

. $(dirname $0)/util.inc

PATTERN_EXCLUDE_FILE=$HOME/code/find-exclude-patterns.txt
EXCLUDED_FILE_ARGS=$(parse_folder_names \
                         "-path ./" \
                         $PATTERN_EXCLUDE_FILE \
                         " -o")

# appending dummy "-name ''" for last pattern string to work correctly
exec find . \
     \( $EXCLUDED_FILE_ARGS -name '' \) -prune -o \
     "$@"
