#!/bin/bash

# wrapper script for find program

if [ $# -lt 1 ]; then
        echo "Usage: $(basename $0) PATTERN"
        exit 1
fi

. $(dirname $0)/util.inc

PATTERN_EXCLUDE_FILE=$HOME/code/exclude-patterns.txt
EXCLUDED_FILE_ARGS=$(parse_folder_names \
                         "-path ./" \
                         $PATTERN_EXCLUDE_FILE \
                         " -o")

# Note: to make it work in emacs byte-compile /usr/share/emacs/24.5/lisp/find-dired.el.gz
# after changing function definition of find-dired()
# 1. appending dummy "-name ''" for last pattern string to work correctly
# 2. appending fake '-printf ""' to make emacs output sane and also not printing pruned dirs
#   -- doesnt work in the normal terminal usage, so disabling this for now
exec find . \
     \( $EXCLUDED_FILE_ARGS -name '' \) -prune -o \
     "$@"
     
