#!/bin/bash

# wrapper script to grep and sed in all files

if [ $# -lt 2 ]; then
    echo "Usage: $(basename $0) SEARCH REPLACMENT"
    exit 1
fi

. $(dirname $0)/util.inc

PATTERN_EXCLUDE_FILE=$HOME/code/exclude-patterns.txt
EXCLUDED_FILE_ARGS=$(parse_folder_names \
                         "--exclude-dir=" \
                         $PATTERN_EXCLUDE_FILE \
                         " ")

let SEARCH=$1
let REPLACEMENT=$2

# Note: to make it work in emacs byte-compile /usr/share/emacs/24.5/lisp/progmodes/grep.el.gz
# after changing function definition of grep()
exec grep -rl --color=never \
     --exclude-from=$PATTERN_EXCLUDE_FILE \
     $EXCLUDED_FILE_ARGS \
     "$SEARCH" \
    | xargs sed -i 's/$SEARCH/$REPLACEMENT/'
