#!/bin/bash

# <add key="fileNumber" value="-1"/>

CONFIG_FILE="c:/msys64/home/ksgaipal/Documents/Cosmos/PullDataFromCosmos/iscopeTool.exe.config"
CMD_EXE="START cmd.exe /C "

function create_xml_tag
{
    echo "<add key=\"fileNumber\" value=\"$1\"\/>"
}

function launch_cmd_in_sequence
{
    local prev_num=-1
    for num in `seq 0 1 1`
    do
        # prepare search format
        local num2=`printf "%02d" $num`
        echo "$prev_num -> $num2"
        local search_text=`create_xml_tag $prev_num`
        local replace_text=`create_xml_tag $num2`

        # replace now
        sed -i "s/$search_text/$replace_text/g" $CONFIG_FILE

        # launch program
        eval $CMD_EXE "echo $num2"
        sleep 1s

        # update counter
        prev_num=$num2

    done
}

launch_cmd_in_sequence
