#!/bin/bash

# wrapper script for saving git diff in temp file and open in default editor

git diff > /tmp/f.diff && (
    if ! [[ -z "$(which emacsclient)" ]]; then
        exec emacsclient -n /tmp/f.diff
    fi

    exec $EDITOR /tmp/f.diff
)
