#!/bin/bash

# wrapper script for grep program

if [ $# -lt 1 ]; then
        echo "Usage: $(basename $0) PATTERN"
        exit 1
fi

. $(dirname $0)/util.inc

PATTERN_EXCLUDE_FILE=$HOME/code/exclude-patterns.txt
EXCLUDED_FILE_ARGS=$(parse_folder_names \
                         "--exclude-dir=" \
                         $PATTERN_EXCLUDE_FILE \
                         " ")

exec grep -nHsI --color=always \
     --exclude-from=$PATTERN_EXCLUDE_FILE \
     $EXCLUDED_FILE_ARGS \
     "$@" * \
    | sed -r 's/[[:space:]]+/ /'
