#!/bin/bash

# wrapper script for program

if [ $# -lt 1 ]; then
    echo "Usage: $(basename $0) PATTERN"
    exit 1
fi

exec rg --type csharp --smart-case --no-heading "$@" \
    | sed -r 's/[[:space:]]+/ /'

